### ISSUE TITLE
Array dependancy 

### ISSUE THREAD

**Issue by r00bal** [MateuszFrankowski/goit-react-hw-04-images#1]
https://github.com/MateuszFrankowski/goit-react-hw-04-images/blob/fdc1475da0182236f3562b44cf142045828e92a4/src/components/App.jsx#L61-L63

Tutaj nie dodałes handleImagesRequest do array dependancy i przez to nie przechodzi Ci build apki. 
Jeżeli funkcji `handleImagesRequest` używasz tylko w useEffetcie, to możesz ją tutaj zdeklarować i odrazu użyć, wtedy nie musisz umieszczać jej  `array dependancy`... a jeżeli używasz jej gdzieś poza useEffect to musisz ją opakować w useCallback i umieścić w   
dependancy:

https://beta.reactjs.org/learn/removing-effect-dependencies

**Comment by MateuszFrankowski** [comment]
musiałem jeszcze pozbyć się dependancy z images. 
Zamiast:
` setImages( images.concat(newImages)); `
 zastosowałem 
`setImages(e => e.concat(newImages));`
